modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "{{license.original}}"

[[mods]]
modId = "{{sideMod.snakeCase}}"
version = "1.6-neoforge-0.0.0"
displayName = "{{sideMod.original}}"
authors = "{{authorHandle.original}} aka {{authorName.original}}"
description = '''
{{description.original}}
'''

[[dependencies.{{sideMod.snakeCase}}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{sideMod.snakeCase}}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.{{sideMod.snakeCase}}]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,1.7.0)"
ordering = "AFTER"
side = "BOTH"